// ============================================================
// DEMO DATA — datos de ejemplo para el modo preview
// ============================================================

export const DEMO_USER = {
  id: 'demo-admin-id',
  email: 'admin@marniediaz.com',
  created_at: '2025-01-01T00:00:00Z',
}

export const DEMO_SESSION = {
  user: DEMO_USER,
  access_token: 'demo-token',
  refresh_token: 'demo-refresh',
  expires_at: Date.now() / 1000 + 86400,
}

const HOY = new Date().toISOString().split('T')[0]
const AYER = new Date(Date.now() - 86400000).toISOString().split('T')[0]
const MAÑANA = new Date(Date.now() + 86400000).toISOString().split('T')[0]

export const DEMO_DATA: Record<string, object[]> = {
  pacientes: [
    { id: 'p1', nombre: 'Andrea', apellido: 'Rodríguez', cedula: '1712345678', sexo: 'femenino', grupo_sanguineo: 'O+', ocupacion: 'Abogada', fecha_nacimiento: '1990-03-15', telefono: '099 886 2001', email: 'andrea.r@gmail.com', direccion: 'La Gasca, Quito', alergias: 'Penicilina', antecedentes: 'Hipertensión controlada', created_at: '2025-01-10T10:00:00Z' },
    { id: 'p2', nombre: 'Carlos', apellido: 'Mendoza', cedula: '1798765432', sexo: 'masculino', grupo_sanguineo: 'A-', ocupacion: 'Contador', fecha_nacimiento: '1955-07-22', telefono: '099 882 6201', email: 'c.mendoza@yahoo.com', direccion: 'La Floresta, Quito', alergias: '', antecedentes: 'Diabético tipo 2. Medicación: Metformina 500mg', created_at: '2025-01-12T11:00:00Z' },
    { id: 'p3', nombre: 'Lucía', apellido: 'Pacheco', cedula: '1723456789', sexo: 'femenino', grupo_sanguineo: 'B+', ocupacion: 'Diseñadora', fecha_nacimiento: '1985-11-08', telefono: '098 765 4321', email: 'lucia.pacheco@hotmail.com', direccion: 'Bellavista, Quito', alergias: '', antecedentes: '', created_at: '2025-02-01T09:00:00Z' },
    { id: 'p4', nombre: 'Roberto', apellido: 'Vásquez', cedula: '1754321098', sexo: 'masculino', grupo_sanguineo: 'O-', ocupacion: 'Ingeniero', fecha_nacimiento: '1972-05-30', telefono: '099 111 2233', email: 'roberto.v@gmail.com', direccion: 'El Batán, Quito', alergias: 'Látex', antecedentes: 'Cardiopatía. Toma aspirina diaria', created_at: '2025-02-15T14:00:00Z' },
    { id: 'p5', nombre: 'María', apellido: 'Torres', cedula: '1765432109', sexo: 'femenino', grupo_sanguineo: 'AB+', ocupacion: 'Estudiante', fecha_nacimiento: '2001-09-14', telefono: '097 654 3210', email: 'maria.torres@gmail.com', direccion: 'Cotocollao, Quito', alergias: '', antecedentes: '', created_at: '2025-03-01T08:00:00Z' },
  ],
  citas: [
    { id: 'c1', paciente_id: 'p1', fecha: AYER, hora: '09:00', motivo: 'Blanqueamiento dental', estado: 'completada', notas: 'Resultado excelente, 8 tonos más blanco', created_at: '2025-03-20T08:00:00Z', pacientes: { nombre: 'Andrea', apellido: 'Rodríguez' } },
    { id: 'c2', paciente_id: 'p2', fecha: HOY, hora: '10:30', motivo: 'Control prótesis parcial', estado: 'confirmada', notas: '', created_at: '2025-03-21T10:00:00Z', pacientes: { nombre: 'Carlos', apellido: 'Mendoza' } },
    { id: 'c3', paciente_id: 'p3', fecha: HOY, hora: '14:00', motivo: 'Endodoncia pieza 16', estado: 'programada', notas: 'Turno de 1.5 horas', created_at: '2025-03-21T12:00:00Z', pacientes: { nombre: 'Lucía', apellido: 'Pacheco' } },
    { id: 'c4', paciente_id: 'p4', fecha: MAÑANA, hora: '08:30', motivo: 'Evaluación para implante', estado: 'programada', notas: 'Verificar radiografía panorámica', created_at: '2025-03-22T09:00:00Z', pacientes: { nombre: 'Roberto', apellido: 'Vásquez' } },
    { id: 'c5', paciente_id: 'p5', fecha: MAÑANA, hora: '11:00', motivo: 'Primera consulta', estado: 'programada', notas: '', created_at: '2025-03-22T10:00:00Z', pacientes: { nombre: 'María', apellido: 'Torres' } },
    { id: 'c6', paciente_id: 'p1', fecha: '2025-03-10', hora: '10:00', motivo: 'Limpieza dental', estado: 'completada', notas: '', created_at: '2025-03-05T09:00:00Z', pacientes: { nombre: 'Andrea', apellido: 'Rodríguez' } },
  ],
  procedimientos: [
    { id: 'pr1', paciente_id: 'p1', cita_id: 'c6', tipo: 'Limpieza', descripcion: 'Profilaxis + aplicación de flúor', costo: 45.00, fecha: '2025-03-10', estado: 'realizado', created_at: '2025-03-10T10:00:00Z', pacientes: { nombre: 'Andrea', apellido: 'Rodríguez' } },
    { id: 'pr2', paciente_id: 'p1', cita_id: 'c1', tipo: 'Blanqueamiento', descripcion: 'Blanqueamiento LED - 8 tonos', costo: 180.00, fecha: AYER, estado: 'realizado', created_at: '2025-03-22T09:00:00Z', pacientes: { nombre: 'Andrea', apellido: 'Rodríguez' } },
    { id: 'pr3', paciente_id: 'p2', cita_id: null, tipo: 'Prótesis', descripcion: 'Prótesis parcial removible superior', costo: 320.00, fecha: '2025-02-20', estado: 'realizado', created_at: '2025-02-20T11:00:00Z', pacientes: { nombre: 'Carlos', apellido: 'Mendoza' } },
    { id: 'pr4', paciente_id: 'p3', cita_id: 'c3', tipo: 'Endodoncia', descripcion: 'Endodoncia pieza 16 - 3 conductos', costo: 150.00, fecha: HOY, estado: 'planificado', created_at: '2025-03-23T08:00:00Z', pacientes: { nombre: 'Lucía', apellido: 'Pacheco' } },
    { id: 'pr5', paciente_id: 'p4', cita_id: null, tipo: 'Consulta', descripcion: 'Evaluación inicial implante pieza 46', costo: 0.00, fecha: MAÑANA, estado: 'planificado', created_at: '2025-03-22T09:00:00Z', pacientes: { nombre: 'Roberto', apellido: 'Vásquez' } },
  ],
  pagos: [
    { id: 'pa1', paciente_id: 'p1', cita_id: 'c6', monto: 45.00, fecha: '2025-03-10', metodo_pago: 'efectivo', estado: 'pagado', notas: 'Pago limpieza', created_at: '2025-03-10T11:00:00Z', pacientes: { nombre: 'Andrea', apellido: 'Rodríguez' } },
    { id: 'pa2', paciente_id: 'p1', cita_id: 'c1', monto: 180.00, fecha: AYER, metodo_pago: 'transferencia', estado: 'pagado', notas: 'Blanqueamiento LED', created_at: '2025-03-22T10:00:00Z', pacientes: { nombre: 'Andrea', apellido: 'Rodríguez' } },
    { id: 'pa3', paciente_id: 'p2', cita_id: null, monto: 200.00, fecha: '2025-02-20', metodo_pago: 'efectivo', estado: 'pagado', notas: 'Abono prótesis', created_at: '2025-02-20T12:00:00Z', pacientes: { nombre: 'Carlos', apellido: 'Mendoza' } },
    { id: 'pa4', paciente_id: 'p2', cita_id: null, monto: 120.00, fecha: '2025-03-05', metodo_pago: 'tarjeta', estado: 'pendiente', notas: 'Saldo prótesis', created_at: '2025-03-05T10:00:00Z', pacientes: { nombre: 'Carlos', apellido: 'Mendoza' } },
    { id: 'pa5', paciente_id: 'p3', cita_id: 'c3', monto: 75.00, fecha: HOY, metodo_pago: 'efectivo', estado: 'pendiente', notas: 'Abono endodoncia', created_at: '2025-03-23T08:00:00Z', pacientes: { nombre: 'Lucía', apellido: 'Pacheco' } },
  ],
  odontograma: [
    { id: 'od1', paciente_id: 'p1', diente_numero: 11, estado: 'obturado', notas: 'Resina clase IV', fecha: '2025-01-15', superficies: { mesial: { simbolo: 'sano', color: null }, distal: { simbolo: 'restauracion', color: 'azul' }, oclusal: { simbolo: 'restauracion', color: 'azul' }, vestibular: { simbolo: 'restauracion', color: 'azul' }, palatino: { simbolo: 'sano', color: null } } },
    { id: 'od2', paciente_id: 'p1', diente_numero: 21, estado: 'corona', notas: 'Corona de porcelana 2022', fecha: '2025-01-15', superficies: { mesial: { simbolo: 'corona', color: 'azul' }, distal: { simbolo: 'corona', color: 'azul' }, oclusal: { simbolo: 'corona', color: 'azul' }, vestibular: { simbolo: 'corona', color: 'azul' }, palatino: { simbolo: 'corona', color: 'azul' } } },
    { id: 'od3', paciente_id: 'p1', diente_numero: 36, estado: 'obturado', notas: 'Amalgama', fecha: '2025-01-15', superficies: { mesial: { simbolo: 'restauracion', color: 'azul' }, distal: { simbolo: 'sano', color: null }, oclusal: { simbolo: 'restauracion', color: 'azul' }, vestibular: { simbolo: 'sano', color: null }, palatino: { simbolo: 'sano', color: null } } },
    { id: 'od4', paciente_id: 'p2', diente_numero: 15, estado: 'extraccion', notas: 'Extracción 2023', fecha: '2025-02-20', superficies: { mesial: { simbolo: 'ausente', color: null }, distal: { simbolo: 'ausente', color: null }, oclusal: { simbolo: 'ausente', color: null }, vestibular: { simbolo: 'ausente', color: null }, palatino: { simbolo: 'ausente', color: null } } },
    { id: 'od5', paciente_id: 'p2', diente_numero: 25, estado: 'extraccion', notas: 'Extracción 2023', fecha: '2025-02-20', superficies: { mesial: { simbolo: 'ausente', color: null }, distal: { simbolo: 'ausente', color: null }, oclusal: { simbolo: 'ausente', color: null }, vestibular: { simbolo: 'ausente', color: null }, palatino: { simbolo: 'ausente', color: null } } },
    { id: 'od6', paciente_id: 'p2', diente_numero: 46, estado: 'caries', notas: 'Caries profunda - requiere endodoncia', fecha: '2025-02-20', superficies: { mesial: { simbolo: 'sano', color: null }, distal: { simbolo: 'caries', color: 'rojo' }, oclusal: { simbolo: 'caries', color: 'rojo' }, vestibular: { simbolo: 'sano', color: null }, palatino: { simbolo: 'sano', color: null } } },
    { id: 'od7', paciente_id: 'p3', diente_numero: 16, estado: 'caries', notas: 'Caries con compromiso pulpar - planificada endodoncia', fecha: HOY, superficies: { mesial: { simbolo: 'caries', color: 'rojo' }, distal: { simbolo: 'caries', color: 'rojo' }, oclusal: { simbolo: 'caries', color: 'rojo' }, vestibular: { simbolo: 'sano', color: null }, palatino: { simbolo: 'sano', color: null } } },
  ],
  fichas_clinicas: [
    {
      id: 'f1',
      paciente_id: 'p1',
      cita_id: 'c6',
      fecha: '2025-03-10',
      motivo_consulta: 'Control post-blanqueamiento dental',
      enfermedad_actual: 'Sensibilidad dental leve en caras vestibulares de incisivos. Inicio: inmediato post-blanqueamiento. Intensidad: 2/10.',
      antecedentes_visita: 'Hipertensión controlada. Niega alergias adicionales a medicamentos.',
      signos_vitales: {
        presion_arterial: '118/76',
        frecuencia_cardiaca: 72,
        frecuencia_respiratoria: 16,
        temperatura_bucal: 36.5,
        temperatura_axilar: 36.4,
        peso: 58.5,
        talla: 166,
      },
      examen_estomatognatico: {
        labios: 'Sin alteraciones. Hidratados. Color normal.',
        mejillas: 'Mucosa bucal normocolorida sin edemas.',
        maxilar_superior: 'Línea media coincidente. Paladar duro normal.',
        maxilar_inferior: 'Simetría normal. Mentón bien definido.',
        lengua: 'Móvil, sin desviaciones, dorso sin alteraciones.',
        paladar: 'Paladar duro con arquitectura normal. Paladar blando sin edemas.',
        piso: 'Piso de boca sin inflamación. Conductillos de Wharton normales.',
        carrillos: 'Carrillos sin patología. Comisuras sin úlceras.',
        glandulas_salivales: 'Parótidas normales. Submandibulares sin aumento de volumen.',
        orofaringe: 'Orofaringe normocolorida sin edema.',
        atm: 'Articulación sin dolor. Movimientos normales. Sin ruidos.',
        ganglios: 'Ganglios submandibulares sin aumento. Cadena cervical normal.',
      },
      odontograma_snapshot: [
        { numero: 11, superficies: { mesial: { simbolo: 'sano', color: null }, distal: { simbolo: 'restauracion', color: 'azul' }, oclusal: { simbolo: 'restauracion', color: 'azul' }, vestibular: { simbolo: 'restauracion', color: 'azul' }, palatino: { simbolo: 'sano', color: null } } },
        { numero: 12, superficies: { mesial: { simbolo: 'sano', color: null }, distal: { simbolo: 'sano', color: null }, oclusal: { simbolo: 'sano', color: null }, vestibular: { simbolo: 'sano', color: null }, palatino: { simbolo: 'sano', color: null } } },
        { numero: 21, superficies: { mesial: { simbolo: 'corona', color: 'azul' }, distal: { simbolo: 'corona', color: 'azul' }, oclusal: { simbolo: 'corona', color: 'azul' }, vestibular: { simbolo: 'corona', color: 'azul' }, palatino: { simbolo: 'corona', color: 'azul' } } },
        { numero: 36, superficies: { mesial: { simbolo: 'restauracion', color: 'azul' }, distal: { simbolo: 'sano', color: null }, oclusal: { simbolo: 'restauracion', color: 'azul' }, vestibular: { simbolo: 'sano', color: null }, palatino: { simbolo: 'sano', color: null } } },
      ],
      indicadores_salud: {
        ihos: 0.8,
        indice_placa: 25,
        indice_calculo: 0,
        indice_sangrado: 0,
        enfermedad_periodontal: 'Encía sana. Sacos < 3mm.',
        maloclusion: 'Normoclusive. Clase I de Angle bilateral.',
        fluorosis: 'Ninguna.',
        cpo: { cariados: 0, perdidos: 0, obturados: 2 },
        ceo: { cariados: 0, perdidos: 0, obturados: 0 },
      },
      observaciones: 'Sensibilidad post-blanqueamiento controlada con enjuague fluorado. Resultado blanqueamiento excelente (8 tonos). Recomendado sensibilidad con pastas para dientes sensibles durante 2 semanas.',
      created_at: '2025-03-10T10:30:00Z',
    },
    {
      id: 'f2',
      paciente_id: 'p1',
      cita_id: null,
      fecha: '2025-02-05',
      motivo_consulta: 'Limpieza preventiva y profilaxis',
      enfermedad_actual: 'Paciente refiere ligera inflamación gingival. Niega dolor. Últimas 2 semanas descuidó higiene por trabajo intenso.',
      antecedentes_visita: 'Hipertensión controlada con Losartán 50mg diario. Niega alergias.',
      signos_vitales: {
        presion_arterial: '120/78',
        frecuencia_cardiaca: 70,
        frecuencia_respiratoria: 16,
        temperatura_bucal: 36.6,
        temperatura_axilar: 36.5,
        peso: 59,
        talla: 166,
      },
      examen_estomatognatico: {
        labios: 'Labios hidratados, color normal.',
        mejillas: 'Mucosa sin alteraciones.',
        maxilar_superior: 'Normal.',
        maxilar_inferior: 'Normal.',
        lengua: 'Móvil, dorso normal.',
        paladar: 'Normal.',
        piso: 'Sin inflamación.',
        carrillos: 'Sin alteraciones.',
        glandulas_salivales: 'Normales.',
        orofaringe: 'Normal.',
        atm: 'Sin síntomas.',
        ganglios: 'Sin aumento de volumen.',
      },
      odontograma_snapshot: [
        { numero: 11, superficies: { mesial: { simbolo: 'sano', color: null }, distal: { simbolo: 'restauracion', color: 'azul' }, oclusal: { simbolo: 'restauracion', color: 'azul' }, vestibular: { simbolo: 'restauracion', color: 'azul' }, palatino: { simbolo: 'sano', color: null } } },
        { numero: 12, superficies: { mesial: { simbolo: 'sano', color: null }, distal: { simbolo: 'sano', color: null }, oclusal: { simbolo: 'sano', color: null }, vestibular: { simbolo: 'sano', color: null }, palatino: { simbolo: 'sano', color: null } } },
        { numero: 21, superficies: { mesial: { simbolo: 'corona', color: 'azul' }, distal: { simbolo: 'corona', color: 'azul' }, oclusal: { simbolo: 'corona', color: 'azul' }, vestibular: { simbolo: 'corona', color: 'azul' }, palatino: { simbolo: 'corona', color: 'azul' } } },
        { numero: 36, superficies: { mesial: { simbolo: 'restauracion', color: 'azul' }, distal: { simbolo: 'sano', color: null }, oclusal: { simbolo: 'restauracion', color: 'azul' }, vestibular: { simbolo: 'sano', color: null }, palatino: { simbolo: 'sano', color: null } } },
      ],
      indicadores_salud: {
        ihos: 1.2,
        indice_placa: 35,
        indice_calculo: 5,
        indice_sangrado: 10,
        enfermedad_periodontal: 'Gingivitis leve. Sacos 2-3mm.',
        maloclusion: 'Normoclusive.',
        fluorosis: 'Ninguna.',
        cpo: { cariados: 0, perdidos: 0, obturados: 2 },
        ceo: { cariados: 0, perdidos: 0, obturados: 0 },
      },
      observaciones: 'Realizada profilaxis completa. Aplicado fluoruro tópico. Paciente instruida en técnica de cepillado. Recomendado usar seda dental diariamente.',
      created_at: '2025-02-05T11:00:00Z',
    },
    {
      id: 'f3',
      paciente_id: 'p2',
      cita_id: null,
      fecha: '2025-02-20',
      motivo_consulta: 'Evaluación prótesis parcial removible y control de caries activa',
      enfermedad_actual: 'Paciente reporta molestias al masticar con prótesis superior izquierda. Dolor mínimo en zona de pieza 46 con palpación.',
      antecedentes_visita: 'Diabetes tipo 2 controlada. Hipertensión. Medicación: Metformina 500mg BID, Lisinopril 10mg diario. Niega alergias.',
      signos_vitales: {
        presion_arterial: '132/84',
        frecuencia_cardiaca: 78,
        frecuencia_respiratoria: 18,
        temperatura_bucal: 36.8,
        temperatura_axilar: 36.7,
        peso: 72.5,
        talla: 172,
      },
      examen_estomatognatico: {
        labios: 'Ligera sequedad. Color normal.',
        mejillas: 'Mucosa sin alteraciones.',
        maxilar_superior: 'Reabsorción alveolar moderada.',
        maxilar_inferior: 'Reabsorción alveolar leve.',
        lengua: 'Móvil. Dorso sin lesiones.',
        paladar: 'Normal.',
        piso: 'Sin patología.',
        carrillos: 'Sin alteraciones.',
        glandulas_salivales: 'Producción salival reducida (diabetes).',
        orofaringe: 'Normal.',
        atm: 'Movimientos normales.',
        ganglios: 'Sin aumento.',
      },
      odontograma_snapshot: [
        { numero: 15, superficies: { mesial: { simbolo: 'ausente', color: null }, distal: { simbolo: 'ausente', color: null }, oclusal: { simbolo: 'ausente', color: null }, vestibular: { simbolo: 'ausente', color: null }, palatino: { simbolo: 'ausente', color: null } } },
        { numero: 25, superficies: { mesial: { simbolo: 'ausente', color: null }, distal: { simbolo: 'ausente', color: null }, oclusal: { simbolo: 'ausente', color: null }, vestibular: { simbolo: 'ausente', color: null }, palatino: { simbolo: 'ausente', color: null } } },
        { numero: 46, superficies: { mesial: { simbolo: 'sano', color: null }, distal: { simbolo: 'caries', color: 'rojo' }, oclusal: { simbolo: 'caries', color: 'rojo' }, vestibular: { simbolo: 'sano', color: null }, palatino: { simbolo: 'sano', color: null } } },
      ],
      indicadores_salud: {
        ihos: 1.8,
        indice_placa: 55,
        indice_calculo: 35,
        indice_sangrado: 30,
        enfermedad_periodontal: 'Periodontitis leve. Sacos 4-5mm en zona posterior.',
        maloclusion: 'Clase II división 1. Resalte aumentado.',
        fluorosis: 'Ninguna.',
        cpo: { cariados: 1, perdidos: 2, obturados: 0 },
        ceo: { cariados: 0, perdidos: 0, obturados: 0 },
      },
      observaciones: 'Prótesis parcial removible bien adaptada. Recomendado mantener higiene meticulosa. Caries en 46 requiere tratamiento inmediato — se planifica endodoncia + obturación. Paciente será citado en 1 semana para procedimiento. Énfasis en control de placa por condición de diabetes.',
      created_at: '2025-02-20T13:00:00Z',
    },
  ],
}
